package com.alainn.soa.rules.discount;

global org.mule.module.bpm.MessageService mule;

dialect "mvel"

rule "Gold"
    lock-on-active
when
$orderSummary : OrderSummary( loyaltyPoints >= 1000 || totalValue >= 150 )
then
	$orderSummary.setDiscountPercentage(0.12);
	$orderSummary.setNewLoyaltyPoints(10);
end

rule "Silver"
    lock-on-active
when
	$orderSummary : OrderSummary( loyaltyPoints >= 500 && < 1000, totalValue >= 100 )
then
	$orderSummary.setDiscountPercentage(0.08);
	$orderSummary.setNewLoyaltyPoints(6);
end

rule "Bronze"
    lock-on-active
when
	$orderSummary : OrderSummary( loyaltyPoints >= 300 && < 500, totalValue >= 80  )
then
	$orderSummary.setDiscountPercentage(0.05);
	$orderSummary.setNewLoyaltyPoints(3);
end
